workflows:
  b-sports-workflow:
    name: BSports
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Bsports API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.Bsports
      vars:
        BUNDLE_ID: "com.Bsports"
        XCODE_SCHEME: "Bsports"
        APP_STORE_APPLE_ID: 6758951311
        NEW_VERSION: "1.1"
        NEW_BUILD: "2"
      xcode: latest
    scripts:
      - name: Set up provisioning profiles
        script: |
          cd $CM_BUILD_DIR/Bsports
          xcode-project use-profiles
      
      - name: Update version and build numbers
        script: |
          cd $CM_BUILD_DIR/Bsports
          
          echo "=== UPDATING VERSION ==="
          echo "Setting version to: $NEW_VERSION"
          echo "Setting build to: $NEW_BUILD"
          
          # Обновляем через agvtool
          agvtool new-marketing-version "$NEW_VERSION"
          agvtool new-version -all "$NEW_BUILD"
          
          # Дополнительно обновляем Info.plist
          find . -name "Info.plist" -type f | while read PLIST; do
            echo "Updating: $PLIST"
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_VERSION" "$PLIST" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$PLIST" 2>/dev/null || true
          done
          
          echo "=== VERIFICATION ==="
          agvtool what-marketing-version
          agvtool what-version
      
      - name: Build IPA
        script: |
          cd $CM_BUILD_DIR/Bsports
          xcode-project build-ipa \
            --project "Bsports.xcodeproj" \
            --scheme "$XCODE_SCHEME"
      
      - name: Upload to App Store Connect
        script: |
          echo "Загружаем билд в App Store Connect..."
          IPA_FILE=$(find $CM_BUILD_DIR -name "*.ipa" -type f | head -1)
          
          if [ -f "$IPA_FILE" ]; then
            echo "Найден IPA: $IPA_FILE"
            echo "Размер: $(du -h "$IPA_FILE" | cut -f1)"
            
            # Проверяем версию в IPA
            TEMP_DIR=$(mktemp -d)
            unzip -q "$IPA_FILE" -d "$TEMP_DIR" 2>/dev/null || true
            PLIST=$(find "$TEMP_DIR" -name "Info.plist" -type f | head -1)
            if [ -f "$PLIST" ]; then
              VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST" 2>/dev/null)
              BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST" 2>/dev/null)
              echo "Версия в IPA: $VERSION ($BUILD)"
            fi
            rm -rf "$TEMP_DIR"
            
            # Загружаем
            app-store-connect publish --path "$IPA_FILE"
          else
            echo "ОШИБКА: IPA файл не найден!"
            find $CM_BUILD_DIR -name "*.ipa" -type f
            exit 1
          fi
    
    artifacts:
      - build/ios/ipa/*.ipa
      - "*.ipa"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
