workflows:
  b-sports-workflow:
    name: BSports
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Bsports API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.Bsports
      vars:
        BUNDLE_ID: "com.Bsports"
        XCODE_SCHEME: "Bsports"
        APP_STORE_APPLE_ID: 6758951311
        NEW_VERSION: "1.1"
        NEW_BUILD: "2"
      xcode: latest
    scripts:
      - name: Set up provisioning profiles
        script: |
          cd $CM_BUILD_DIR/Bsports
          xcode-project use-profiles
      
      - name: Update version and build numbers
        script: |
          cd $CM_BUILD_DIR/Bsports
          
          echo "=== UPDATING VERSION ==="
          echo "Setting version to: $NEW_VERSION"
          echo "Setting build to: $NEW_BUILD"
          
          # Обновляем напрямую через PlistBuddy (более надежный способ)
          echo "Updating Info.plist files..."
          find "$CM_BUILD_DIR/Bsports" -name "Info.plist" -type f | while read PLIST; do
            echo "Updating: $PLIST"
            # Устанавливаем версию и билд
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_VERSION" "$PLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $NEW_VERSION" "$PLIST" 2>/dev/null
            
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$PLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $NEW_BUILD" "$PLIST" 2>/dev/null
            
            # Проверяем
            VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST" 2>/dev/null)
            BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST" 2>/dev/null)
            echo "  -> Version: $VERSION, Build: $BUILD"
          done
          
          # Обновляем project.pbxproj
          echo "Updating project.pbxproj files..."
          find "$CM_BUILD_DIR/Bsports" -name "project.pbxproj" -type f | while read PBXPROJ; do
            echo "Found: $PBXPROJ"
            # Создаем бэкап
            cp "$PBXPROJ" "${PBXPROJ}.backup"
            # Обновляем MARKETING_VERSION и CURRENT_PROJECT_VERSION
            sed -i '' "s/MARKETING_VERSION = [0-9.]*;/MARKETING_VERSION = $NEW_VERSION;/g" "$PBXPROJ" 2>/dev/null || true
            sed -i '' "s/CURRENT_PROJECT_VERSION = [0-9.]*;/CURRENT_PROJECT_VERSION = $NEW_BUILD;/g" "$PBXPROJ" 2>/dev/null || true
            echo "  Updated project settings"
          done
          
          # Пробуем использовать agvtool с указанием проекта
          echo "Trying agvtool with specific project..."
          cd "$CM_BUILD_DIR/Bsports"
          if [ -f "Bsports.xcodeproj/project.pbxproj" ]; then
            # Создаем временный файл с настройками для agvtool
            echo "Project found, using agvtool..."
            agvtool new-marketing-version "$NEW_VERSION" -project Bsports.xcodeproj 2>/dev/null || true
            agvtool new-version -all "$NEW_BUILD" -project Bsports.xcodeproj 2>/dev/null || true
          fi
          
          echo "=== VERIFICATION ==="
          # Проверяем финальные значения
          FIRST_PLIST=$(find "$CM_BUILD_DIR/Bsports" -name "Info.plist" -type f | head -1)
          if [ -f "$FIRST_PLIST" ]; then
            FINAL_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$FIRST_PLIST" 2>/dev/null)
            FINAL_BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$FIRST_PLIST" 2>/dev/null)
            echo "Final version in Info.plist: $FINAL_VERSION ($FINAL_BUILD)"
          else
            echo "No Info.plist found for verification"
          fi
      
      - name: Build IPA
        script: |
          cd $CM_BUILD_DIR/Bsports
          echo "Building IPA with version $NEW_VERSION ($NEW_BUILD)"
          xcode-project build-ipa \
            --project "Bsports.xcodeproj" \
            --scheme "$XCODE_SCHEME"
      
      - name: Upload to App Store Connect
        script: |
          echo "Загружаем билд в App Store Connect..."
          IPA_FILE=$(find $CM_BUILD_DIR -name "*.ipa" -type f | head -1)
          
          if [ -f "$IPA_FILE" ]; then
            echo "Найден IPA: $IPA_FILE"
            echo "Размер: $(du -h "$IPA_FILE" | cut -f1)"
            
            # Проверяем версию в IPA
            TEMP_DIR=$(mktemp -d)
            unzip -q "$IPA_FILE" -d "$TEMP_DIR" 2>/dev/null || true
            PLIST=$(find "$TEMP_DIR" -name "Info.plist" -type f | head -1)
            if [ -f "$PLIST" ]; then
              VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST" 2>/dev/null)
              BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST" 2>/dev/null)
              echo "Версия в IPA: $VERSION ($BUILD)"
            fi
            rm -rf "$TEMP_DIR"
            
            # Загружаем
            app-store-connect publish --path "$IPA_FILE"
          else
            echo "ОШИБКА: IPA файл не найден!"
            find $CM_BUILD_DIR -name "*.ipa" -type f
            exit 1
          fi
    
    artifacts:
      - build/ios/ipa/*.ipa
      - "*.ipa"
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true  # Если хотите отправлять в TestFlight сразу
